import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { store } from "./store/index";
import axios from "axios";
import bootstrap from "bootstrap";
import "./assets/style.css";
import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
const app = createApp(App);
app.use(router);
app.use(store);
app.config.globalProperties.$http = axios;
app.use(bootstrap);
app.mount("#app");
